### ISSUE TITLE
Debounce not working as expected

### ISSUE THREAD

**Issue by hipwelljo** [danydev/DORateLimit#1]
When using debounce, it's not working as I expected. I'm using it to limit how often a network request is made while the user is typing into a text field, debounce should run the block every time the threshold is met, but then again a final time after it's met for the last time to ensure the entire search phrase is submitted, not settling with a partial string. That's not the behavior I'm seeing.

When using
`RateLimit.debounce("reload", threshold: 0.75) {
    print("loading: " + self.searchTerm)
}`

and calling this method every time a character is typing into the field, typing "universe" really quickly, it only prints a single time: "loading: u". I expected it to print twice, with "u" and "universe".

**Comment by danydev** [comment]
The current implementation is based on the definition of throttling and debouncing that you can find here http://benalman.com/projects/jquery-throttle-debounce-plugin/
Basically on debounce you can have an `atBegin` Bool: if this is true, your function is immediately called and debounced if called within the threshold. If this is false, your function is called only at the very end of the threshold.
I agree that would be cool to expand the debounce offering also an `atEnd` optional Bool, so that you can cover your use case, but currently it works as intended.

**Comment by hipwelljo** [comment]
@danydev  Interesting, supplying `false` for `atBegin` is actually calling the function twice in the case I type very slowly one character at a time. It works great when typing fast, but most users will be typing really slow on this platform (tvOS) so this is actually going to double my network requests for most users. :O For example typing "u" (calling the function once) it immediately executes the block, then after 0.75 seconds it executes it again (even though I didn't type any more characters to call the function again).

Is that working as intended - it seems it shouldn't be calling it at begin when `atBegin` is `false`. :)

**Comment by danydev** [comment]
@hipwelljo yes, you are right, it shouldn't be calling it at begin when `atBegin` is false. I just performed a quick fix and pushed on master. Can you verify it? I need to add couple of unit tests to avoid regressions like this one :)

**Comment by hipwelljo** [comment]
@danydev It's fixed, and working well for me. Thanks much!
